"""Web Push (VAPID) — fachada de reexportación.

La implementación vive en subscriptions, payloads, notify y test_push.
"""
from __future__ import annotations

from sira.services.push.notify import (
    _aemet_match_subscription,
    _incendio_match_subscription,
    _meteo_should_notify,
    _push_gone,
    _save_state,
    _sismo_match_subscription,
    _split_meteo_bootstrap,
    _state,
    _sub_zona_geo,
    _tsunami_match_subscription,
    notify_new_alerts,
    notify_new_meteo_alerts,
    send_push,
)
from sira.services.push.payloads import (
    _build_aemet_payload,
    _build_incendio_payload,
    _build_payload,
    _build_tsunami_payload,
    _fmt_parametro_push,
    _sub_prefers_incendio,
    _sub_prefers_meteo,
    _sub_prefers_sismo,
    _sub_prefers_tsunami,
)
from sira.services.push.subscriptions import (
    _get_vapid_signer,
    _needs_normalize,
    _normalize_sub,
    _subscription_info,
    add_subscription,
    list_subscriptions,
    remove_subscription,
    save_subscriptions,
    vapid_enabled,
    vapid_public_key,
)
from sira.services.push.test_push import (
    debug_aemet_matches,
    debug_push_state,
    send_bootstrap_meteo_for_subscription,
    send_test_meteo_push,
    send_test_push,
)

__all__ = [
    "_aemet_match_subscription",
    "_build_aemet_payload",
    "_build_incendio_payload",
    "_build_payload",
    "_build_tsunami_payload",
    "_fmt_parametro_push",
    "_get_vapid_signer",
    "_incendio_match_subscription",
    "_meteo_should_notify",
    "_needs_normalize",
    "_normalize_sub",
    "_push_gone",
    "_save_state",
    "_sismo_match_subscription",
    "_split_meteo_bootstrap",
    "_state",
    "_sub_prefers_incendio",
    "_sub_prefers_meteo",
    "_sub_prefers_sismo",
    "_sub_prefers_tsunami",
    "_sub_zona_geo",
    "_subscription_info",
    "_tsunami_match_subscription",
    "add_subscription",
    "debug_aemet_matches",
    "debug_push_state",
    "list_subscriptions",
    "notify_new_alerts",
    "notify_new_meteo_alerts",
    "remove_subscription",
    "save_subscriptions",
    "send_bootstrap_meteo_for_subscription",
    "send_push",
    "send_test_meteo_push",
    "send_test_push",
    "vapid_enabled",
    "vapid_public_key",
]
